global using System;
global using System.Collections;
global using System.Collections.Immutable;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reactive;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Threading.Channels;
global using Stl;
global using Stl.Async;
global using Stl.Benchmarking;
global using Stl.Collections;
global using Stl.Reflection;
global using Stl.Serialization;
global using Stl.Text;
global using Stl.Time;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;

global using static System.Console;
global using static Samples.RpcBenchmark.Program;
